#include "../main_display.h"

CONTAINER_INIT_FUNC(CONTROL_MAIN)
{
    lv_obj_t* container = SCR_C(CONTROL_MAIN);
    SIZEANDALIGN(600, 0, 200, 480, LV_ALIGN_TOP_LEFT)
}

CONTAINER_INIT_FUNC(CONTROL_AREA_1)
{
    lv_obj_t* container = SCR_C(CONTROL_AREA_1);
    SIZEANDALIGN(0, 0, 200, 340, LV_ALIGN_TOP_LEFT)
}

CONTAINER_INIT_FUNC(CONTROL_AREA_2)
{
    lv_obj_t* container = SCR_C(CONTROL_AREA_2);
    SIZEANDALIGN(0, 340, 200, 140, LV_ALIGN_TOP_LEFT)
}