#include "../main_display.h"

CONTAINER_INIT_FUNC(VISUAL_MAIN)
{
    lv_obj_t* container = SCR_C(VISUAL_MAIN);
    SIZEANDALIGN(0, 0, 600, 480, LV_ALIGN_TOP_LEFT)
}

CONTAINER_INIT_FUNC(VISUAL_AREA_1)
{
    lv_obj_t* container = SCR_C(VISUAL_AREA_1);
    SIZEANDALIGN(0, 0, 200, 480, LV_ALIGN_TOP_LEFT)
}

CONTAINER_INIT_FUNC(VISUAL_G_C)
{
    lv_obj_t* container = SCR_C(VISUAL_G_C);
    SIZEANDALIGN(200, 0, 400, 480, LV_ALIGN_TOP_LEFT)
}

CONTAINER_INIT_FUNC(VISUAL_AREA_2)
{
    lv_obj_t* container = SCR_C(VISUAL_AREA_2);
    SIZEANDALIGN(0, 0, 400, 400, LV_ALIGN_TOP_LEFT)
}

CONTAINER_INIT_FUNC(VISUAL_AREA_3)
{
    lv_obj_t* container = SCR_C(VISUAL_AREA_3);
    SIZEANDALIGN(0, 400, 400, 80, LV_ALIGN_TOP_LEFT)
}